version: 0.0.1
metadata:
  code: RQAPI
  name: rqapi
  description: Test repository for RestQA
environments:
  - name: local
    default: true
    plugins:
      - name: "@restqa/restqapi"
        config:
          url: http://localhost:9999
      - name: "@restqa/http-mock-plugin"
        config:
          folder: ./stubs
          debug: false
          port: 8888
          envs:
            TYPICODE: typicode
